from building import *
import os

cwd = GetCurrentDir()
src = []

CPPPATH = [cwd + '/../include']
group = []

if GetDepend(['RT_USING_RTC']):
    src = src + ['dev_rtc.c']
    if GetDepend(['RT_USING_ALARM']):
        src = src + ['dev_alarm.c']
    if GetDepend(['RT_USING_SOFT_RTC']):
        src = src + ['dev_soft_rtc.c']

    if os.path.isfile(os.path.join(cwd, 'chips', 'SConscript')):
        group = group + SConscript(os.path.join('chips', 'SConscript'))

group = group + DefineGroup('DeviceDrivers', src, depend = ['RT_USING_RTC'], CPPPATH = CPPPATH)

Return('group')
