# SConscript for RTC chip drivers

from building import *
import os

cwd = GetCurrentDir()
objs = []

if not GetDepend(['RT_USING_RTC']):
    Return('objs')

for d in os.listdir(cwd):
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs += SConscript(os.path.join(d, 'SConscript'))

Return('objs')
